version: '3.7'

services:
  todo-list:
    container_name: todo-list
    image: diamol/ch09-todo-list
    ports:
      - '8050:80'
    networks:
      - todo-list-network

  prometheus:
    container_name: prometheus
    build:
      context: ./servuces/Prometheus
      dockerfile: Dockerfile
    ports:
        - '9090:9090'
    networks:
        - todo-list-network

  grafana:
    container_name: grafana
    build:
      context: ./servuces/Grafana
      dockerfile: Dockerfile
    ports:
        - '3000:3000'
    depends_on:
      - prometheus
    networks:
        - todo-list-network

networks:
    todo-list-network:
